import 'dart:core';
import 'package:flutter/material.dart';
import '../generate.dart';
import 'package:flutter_code_push_next/index.dart';

class WTPopupMenuItemGeneric {
  static void init() {
    Map<String, Map<String, Function>> genericMap = {};
    WTPopupMenuItem().genericMap = genericMap;
    genericMap["PopupMenuItem"] = _genericFunctionMap("PopupMenuItem");
  }

  static Map<String, Function> _genericFunctionMap(String methodName) {
    Function function = WTPopupMenuItem().attributesMap!['PopupMenuItem'];
    Map<String, Function> functionMap = {
      "String": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<String>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory1": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem1>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory2": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem2>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory3": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem3>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory4": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem4>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory5": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem5>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory6": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem6>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory7": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem7>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory8": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem8>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory9": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem9>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory10": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem10>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory11": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem11>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory12": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem12>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory13": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem13>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory14": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem14>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory15": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem15>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory16": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem16>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory17": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem17>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory18": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem18>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory19": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem19>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory20": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem20>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory21": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem21>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory22": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem22>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory23": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem23>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory24": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem24>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory25": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem25>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory26": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem26>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory27": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem27>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory28": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem28>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory29": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem29>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory30": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem30>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory31": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem31>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory32": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem32>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory33": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem33>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory34": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem34>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory35": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem35>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory36": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem36>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory37": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem37>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory38": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem38>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory39": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem39>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory40": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem40>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory41": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem41>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory42": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem42>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory43": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem43>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory44": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem44>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory45": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem45>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory46": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem46>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory47": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem47>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory48": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem48>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory49": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem49>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory50": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem50>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "Text": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<Text>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory1": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem1>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory2": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem2>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory3": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem3>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory4": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem4>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory5": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem5>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory6": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem6>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory7": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem7>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory8": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem8>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory9": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem9>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory10": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem10>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory11": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem11>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory12": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem12>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory13": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem13>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory14": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem14>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory15": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem15>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory16": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem16>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory17": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem17>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory18": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem18>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory19": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem19>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory20": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem20>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory21": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem21>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory22": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem22>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory23": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem23>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory24": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem24>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory25": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem25>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory26": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem26>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory27": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem27>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory28": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem28>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory29": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem29>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory30": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem30>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory31": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem31>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory32": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem32>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory33": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem33>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory34": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem34>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory35": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem35>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory36": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem36>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory37": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem37>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory38": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem38>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory39": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem39>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory40": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem40>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory41": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem41>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory42": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem42>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory43": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem43>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory44": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem44>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory45": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem45>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory46": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem46>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory47": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem47>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory48": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem48>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory49": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem49>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
      "WTEnumMemory50": ({
        key,
        value,
        onTap,
        enabled = true,
        height = kMinInteractiveDimension,
        padding,
        textStyle,
        mouseCursor,
        child,
      }) {
        return function<WTEnumMemory<TypeSystem50>>(
          key: key,
          value: value,
          onTap: onTap,
          enabled: enabled,
          height: height,
          padding: padding,
          textStyle: textStyle,
          mouseCursor: mouseCursor,
          child: child,
        );
      },
    };
    return functionMap;
  }
}
