import 'dart:core';
import 'package:flutter/material.dart';
import '../generate.dart';
import 'package:flutter_code_push_next/index.dart';

class WTRadioListTileGeneric {
  static void init() {
    Map<String, Map<String, Function>> genericMap = {};
    WTRadioListTile().genericMap = genericMap;
    genericMap["RadioListTile"] = _genericFunctionMap("RadioListTile");
  }

  static Map<String, Function> _genericFunctionMap(String methodName) {
    Function function = WTRadioListTile().attributesMap!['RadioListTile'];
    Map<String, Function> functionMap = {
      "double": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<double>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory1": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem1>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory2": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem2>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory3": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem3>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory4": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem4>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory5": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem5>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory6": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem6>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory7": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem7>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory8": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem8>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory9": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem9>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory10": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem10>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory11": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem11>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory12": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem12>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory13": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem13>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory14": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem14>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory15": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem15>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory16": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem16>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory17": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem17>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory18": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem18>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory19": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem19>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory20": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem20>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory21": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem21>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory22": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem22>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory23": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem23>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory24": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem24>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory25": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem25>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory26": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem26>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory27": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem27>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory28": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem28>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory29": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem29>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory30": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem30>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory31": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem31>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory32": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem32>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory33": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem33>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory34": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem34>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory35": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem35>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory36": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem36>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory37": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem37>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory38": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem38>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory39": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem39>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory40": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem40>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory41": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem41>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory42": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem42>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory43": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem43>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory44": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem44>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory45": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem45>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory46": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem46>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory47": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem47>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory48": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem48>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory49": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem49>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "WTEnumMemory50": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<WTEnumMemory<TypeSystem50>>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "Locale": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<Locale>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "TargetPlatform": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<TargetPlatform>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "ThemeMode": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<ThemeMode>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
      "int": ({
        key,
        value,
        groupValue,
        onChanged,
        toggleable = false,
        activeColor,
        title,
        subtitle,
        isThreeLine = false,
        dense,
        secondary,
        selected = false,
        controlAffinity = ListTileControlAffinity.platform,
        autofocus = false,
        contentPadding,
        shape,
        tileColor,
        selectedTileColor,
      }) {
        return function<int>(
          key: key,
          value: value,
          groupValue: groupValue,
          onChanged: onChanged,
          toggleable: toggleable,
          activeColor: activeColor,
          title: title,
          subtitle: subtitle,
          isThreeLine: isThreeLine,
          dense: dense,
          secondary: secondary,
          selected: selected,
          controlAffinity: controlAffinity,
          autofocus: autofocus,
          contentPadding: contentPadding,
          shape: shape,
          tileColor: tileColor,
          selectedTileColor: selectedTileColor,
        );
      },
    };
    return functionMap;
  }
}
